### ISSUE TITLE
Build against Cake 0.22.0

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Codecov#13]
Build against Cake 0.22.0 to support Cake versions >= 0.22.0

**Comment by larzw** [comment]
thanks @pascalberger,

I will try and get to it this weekend.

**Comment by AdmiringWorm** [comment]
@larzw I think this should potentially be considered a `breaking change`, especially considering the .NET Framework version needs to be changed to `4.6`

**Comment by devlead** [comment]
It's also possible to target Cake 0.21.1 for .NET 4.5 like I did here
https://github.com/cake-contrib/Cake.Incubator/pull/48/files#diff-c2f3210fd2a029ab440d1ed23e0e4f28R49

**Comment by larzw** [comment]
@pascalberger,

This is fixed now.
