### ISSUE TITLE
GitVersion is breaking the build now.

### ISSUE THREAD

**Issue by larzw** [cake-contrib/Cake.Codecov#15]
During the pack task, a call to gitverson seams to cause an error. See:
https://ci.appveyor.com/project/cakecontrib/cake-codecov/branch/master

**Comment by AdmiringWorm** [comment]
I tried to look into it, unfortunately I couldn't figure out why that is happening.
I did test it after rebasing the other branch (the one with the work on using Cake.Recipe), and that one doesn't seem to have any problems.

I'll try finishing up the work there, and see how it goes.
