### ISSUE TITLE
Support for Cake.Core 0.26

### ISSUE THREAD

**Issue by twenzel** [cake-contrib/Cake.Codecov#17]
Please provide a version supporting Cake.Core 0.26.

**Comment by larzw** [comment]
Thanks for the suggestion, @AdmiringWorm are you cool with this?

**Comment by AdmiringWorm** [comment]
@larzw sure, but it would probably be best to add it in a non-breaking way.

By just targeting 0.26 for netstandard2.0 IMO, and keeping the rest frameworks with the existing dependencies.

**Comment by AdmiringWorm** [comment]
Seems like it will be a Breaking change anyhow, unable to target previous versions for the .NET 4.6 Framework
