### ISSUE TITLE
Providing unit test coverage for Codecov addin

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Codecov#2]
I noticed there wasn't any coverage report yet for this Codecov addin.
Perhaps consider dogfooding the built addin to provide it?

I believe it may be possible to do with the [CakeExecuteExpression](http://cakebuild.net/api/Cake.Common.Tools.Cake/CakeAliases/34FA2696).

If interested I could look into exactly that sometime during this weekend.

/cc @larzw

**Comment by larzw** [comment]
Hi @AdmiringWorm,
I just gave you write access... We definitely should add coverage. One issue I ran into is I use
```csharp
// setup.cake
Task("Tests").IsDependentOn("Build").Does(() =>
{
	DotNetCoreTest(...);
});
```
and I'm not sure we can use opencover with this. An alternative solution is given in, https://github.com/OpenCover/opencover/issues/601.

As far as dogfooding, would using *CakeExecuteExpression* be any better than just taking the *n-1* version of the addin? For example, right now we can use version 0.2.0 in the build script

```csharp
#addin nuget:?package=Cake.Codecov&version=0.2.0
```
but I"m open to suggestions!

Thanks!

**Comment by AdmiringWorm** [comment]
I thought I already had write access, well no matter.

Regarding the OpenCover issue you mentioned, unless I'm blind they suggest using Full debug build?
I'm against that personally, I've found changing the debug build to use normal pdf debug instead of portable works just fine`<DebugType>pdbonly</DebugType>` ( of course this needs to be done for both the library, and the unit tests library).

Of course using OpenCover requires some special logic as it only works on Windows (not too hard to do though, https://github.com/WormieCorp/Cake.Transifex/blob/master/build.cake#L135-L145)

Regarding the reference to n-1 version of the adding vs the dogfooding, that could perhaps be boiled down to a personal opinion.
I'm thinking of it like this, **detect early**. Lets say some unit tests was forgotten so everything passes and works well, if referencing the previous version no errors would actually be reported. But by dogfooding the built version, if something fails it fails instantly (which could be useful if a new version is just about to be pushed).

Another reason could also be (although unlikely), if some new feature is added in the new version and wishes to make use of it we could use it now instead of pushing another version first.

Third reason IMO, we don't have to download it when it's not needed (save bandwidth if you will, yeah yeah bandwidth may be cheap, but still).

**Comment by larzw** [comment]
My bad, you did already have write access (I did not notice the Teams)....I like your suggestion of using *pdbonly* and your explanation of why we would use dogfooding...Thanks!

> "it only works on Windows"

and currently so does the tool https://github.com/codecov/codecov-exe/blob/master/Source/Codecov/Upload/Upload.cs#L21. It's a .NET Core app, so OS X and Linux builds will come. I ran into an issue using the HTTP library on OS X. I'll need to revisit it...

**Comment by AdmiringWorm** [comment]
> and currently so does the tool https://github.com/codecov/codecov-exe/blob/master/Source/Codecov/Upload/Upload.cs#L21.

And rightfully so, at least until support for SharpCover is added to codecov, or someone not developing in C# requests it.

> It's a .NET Core app, so OS X and Linux builds will come

While using .NET Core makes is simpler to do cross-platform development, there probably is a few cases where additional logic needs to be separated between the different OS's (mostly because .NET Core isn't mature enough though).

> I ran into an issue using the HTTP library on OS X. I'll need to revisit it...

Don't get me started on OS X, I've never actually used OS X more than probably 1-2 hours in total in the last 10-12 years or so, so that's one area I pretty much can't do anything (as well as there is some bugs in .NET Core which makes it almost impossible to build/running unit tests on OS X, when building on travis)

Anyways, I'll look into dogfooding the addin tomorrow (I should actually already gone to bed now, almost 4 a.m.)

**Comment by AdmiringWorm** [comment]
Unfortunately life got in the way, so I've yet to look into dogfooding the addin.
Hopefully I'll have the time to look into it sometime in the coming week.

**Comment by larzw** [comment]
I've added coverage using the n-1 release of the Cake.Codecov addin. I used your suggestion of setting the debug type to pdbonly. Feel free to get the dogfooding working using CakeExecuteExpression whenever. Thanks again!

**Comment by AdmiringWorm** [comment]
Sorry, I've had my hands full this whole week so haven't been able to look into dogfooding the addin previously.
Just started looking into it now though (just need to resolve a problem with nuget not restoring packages on my machine first).

I'll commit to a feature branch when I believe I have something that may work, before merging it into the master branch.

**Comment by AdmiringWorm** [comment]
Alright, so I got something that works (see the [feature/dogfooding-addin](https://github.com/cake-contrib/Cake.Codecov/tree/feature/dogfooding-addin) branch.

However, there is still an issue with it mapping to the correct files (because using `CakeExecuteExpression` is compiled and ran from a temporary location.
Will probably need to add a codecov.yml file and provide path fixes.
