### ISSUE TITLE
The assembly 'Cake.Codecov, Version=1.0.0.0 is referencing an older version of Cake.Core (0.22.0)

### ISSUE THREAD

**Issue by asterixorobelix** [cake-contrib/Cake.Codecov#20]
Hi Team

I am using the Wyam [Cake Recipe](https://github.com/cake-contrib/Cake.Recipe/blob/develop/build.ps1) but am experiencing the following error:
```powershell
Error: The assembly 'Cake.Codecov, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```
Do you think you could point me in the direction of how to fix this?

**Comment by AdmiringWorm** [comment]
have you made sure that there isn't an old version of Cake.Codecov located in the tools directory?

If the tools directory isn't cleaned it wouldn't download the latest version.

**Comment by asterixorobelix** [comment]
Thanks @AdmiringWorm . Forgive my ignorance, but how would one go about downgrading Cake?

Sidenote - I just got the build to succeed by deleting the tools folder and using this [build.cake](https://github.com/daveaglick/daveaglick/blob/master/build.cake). I see that it is from December 2017. Is that what you mean about using a build.cake which references an older version of cake?

**Comment by AdmiringWorm** [comment]
Downgrading Cake would mean to change the cake version in the  `./tools/packages.config` file.

This file is usually cached on build server.

Basically what you'll want it to be is the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
    <package id="Cake" version="0.25.0" />
</packages>
```
the version can be changed to the latest when cake.recipe supports it.

The reason why you got the build working again after you changed the build.cake file, is because it now no longer uses Cake.Recipe, and therefore not Cake.Codecov as well.

**Comment by AdmiringWorm** [comment]
@asterixorobelix I apologise for being silent for so long.
I've somehow completely missed your last comment.

I just wanted to follow up to see if you ever managed to resolve the problem you experienced?

**Comment by AdmiringWorm** [comment]
I will be closing this issue, if you still believe it to be relevant, and/or more need to be discussed, then feel free to re-open this issue.
