### ISSUE TITLE
Changed AppVeyor Build Number not detected.

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Codecov#6]
Just changed one of my projects to use `Cake.Codecov` and which changes the build version of AppVeyor (using GitVersion) and this change was not detected when trying to upload the coverage report.

The codecov tool still detected the old build version, and since I believe this is pretty much related to being run from Cake we should consider perhaps adding some detection logic in the `Cake.Codecov` addin to grab the build number. Perhaps by reading the environment variable set by gitversion (`GitVersion_SemVer`) and if it exists, use the output from the mentioned environment variable, append `.build` and appending the `APPVEYOR_BUILD_NUMBER`. (Or more simplified, using the `APPVEYOR_BUILD_VERSION`).

I'm still testing it what's best on my own project, to see the best aproach, but opening this for tracking.

**Comment by AdmiringWorm** [comment]
Looks like this requires to read both `GitVersion_FullSemVer` and `APPVEYOR_BUILD_NUMBER`.
Instead of having this done automatically, perhaps we could provide an option in the settings to provide such parsing?

**Comment by AdmiringWorm** [comment]
Looks like all set environment variables isn't available until after cake have finished its execution. Seems like this will need to be up to the user anyhow.

Too bad, as the upload would seem broken by any user using GitVersion.

**Comment by AdmiringWorm** [comment]
Ops, didn't mean to close it XD

**Comment by AdmiringWorm** [comment]
Okay, so unless there is a way to override the job argument that `codecov-exe` sends to codecov.io, then this is pretty much blocked until there is a way.

**Comment by larzw** [comment]
Thanks for finding this...I double checked my AppVeyor code in codecov-exe and it's the same as the bash and python uploader. I think it's just a bug in general. I noticed the bug when I clicked on the hyperlink to the appveyor build in codecov (it's broken). Was this the place where you noticed the bug? Just curious if there are other places. Maybe the commandline args `build` will help? Thanks!

**Comment by AdmiringWorm** [comment]
> I noticed the bug when I clicked on the hyperlink to the appveyor build in codecov (it's broken). Was this the place where you noticed the bug?

No, I noticed it first when trying to upload a coverage report from my [Cake.Transifex](https://github.com/WormieCorp/Cake.Transifex) project.

I first tried to use the `Build` argument, but that doesn't help anything unfortunately.
As seen here: https://ci.appveyor.com/project/AdmiringWorm/cake-transifex/build/0.3.0-alpha.8.build.42#L317 (Look at line 317-324)
It's the `job` argument that needs to be overridden.
But as I mentioned, I found out why it happens, until cake have finished the execution the environment variables isn't updated.
As such, I don't think there is any way to fix this problem in the library (or in the executable either).

The current workaround I had to do was to create/update the necessary environment that should have been passed with the `job` argument.
https://github.com/WormieCorp/Cake.Transifex/blob/develop/build.cake#L159-L166

I'm thinking, we should perhaps mention this workaround in the Readme.md somewhere. Thoughts?

**Comment by AdmiringWorm** [comment]
If there is a better workaround that could be implemented in the addin library though, that would be better.
But I can't see any way to make that happen.

**Comment by larzw** [comment]
What if I exposed `Job` in the commandline of codecov-exe. Any you could override it?

**Comment by AdmiringWorm** [comment]
while that certainly would be an option, it could be a little wrong in this case.
I looked a little at the source of codecov-exe, and noticed the job variable is constructed from three different environment variables.
In this case, using the `Job` parameter directly would probably be more of a pain than manually setting the `APPVEYOR_BUILD_VERSION` environment variable when calling Codecov in the cake script (Using `ToolSettings.EnvironmentVariable` Property).

An option to only pass the build version perhaps could be possible instead (not in the codecov-exe program, but only in the addin library)?

**Comment by AdmiringWorm** [comment]
That Property could perhaps basically just set the `APPVEYOR_BUILD_VERSION` and other known environment values used to generate the job argument.

**Comment by larzw** [comment]
Yeah I agree with that! Allowing an override in the codecov-exe is not the best option.

> An option to only pass the build version perhaps could be possible instead (not in the codecov-exe program, but only in the addin library

I'm cool with that or just documenting it in the readme.

**Comment by AdmiringWorm** [comment]
Ops, forgot to reply XD.
I think documenting it would be for the best at first (perhaps under a section called `KNOWN ISSUES`), and perhaps at some point if enough people request it we should add an option to pass in the build version, or something else.

**Comment by AdmiringWorm** [comment]
A quick example I'm thinking to perhaps add to the bottom of the README file:

## Known Issues
- Coverage report upload fails when using gitversion (or other tools that change the appveyor build version)
  Workaround: Add the following in your `Upload Coverage task`
  ```csharp
  Task("Upload-Coverage")
      .Does(() =>
  {
      var buildVersion = string.Format("{0}.build.{1}",
          variableThatStores_GitVersion_FullSemVer,
          BuildSystem.AppVeyor.Environment.Build.Version
      );
      var settings = new CodecovSettings {
          Files = new[] { "coverage.xml" },
          EnvironmentVariables = new Dictionary<string,string> { { "APPVEYOR_BUILD_VERSION", buildVersion } }
      };
      Codecov(settings);
  });
  ```

Thoughts?

**Comment by larzw** [comment]
I like it!

On another note,if you want, feel free to update the readme file at the end with your handle..

`Feel free to open an issue or ask a question in Gitter by tagging us: @larzw and/or @AdmiringWorm.`

and the copyright in the License file and `Cake.Codecov.csproj`:

`Copyright (c) 2017 Larz White and Kim J. Nordmo`

I'll add you as an owner on Nuget too.

**Comment by AdmiringWorm** [comment]
Sure thing, I'll do that.
Not sure about editing the License and Cake.Codecov.csproj though.
You're the one that actually done the work, I just added the dogfooding of the addin.

**Comment by AdmiringWorm** [comment]
I'm pushing out the change to the Readme.md, when I eventually make a change to the actual addin code I'll update the license and csproj

**Comment by larzw** [comment]
Should we close this now?

**Comment by AdmiringWorm** [comment]
I'm not sure, the issue isn't exactly fixed. Only mentioned.
But could probably close it and add the `Wontfix` label (I added a few new labels earlier today)
